[uwsgi]
chdir = /home/test/upload
#项目根目录
module = upload.wsgi:application
#指定wsgi模块下的application对象
http = 0.0.0.0:8000
#对本机8000端口提供服务
master = true
#主进程

processes = 2
# 进程数
threads = 4
# 线程数

vacuum = true
#退出、重启时清理文件
daemonize = ./run.log
#日志文件
disable-logging = true
#不记录正常信息，只记录错误信息
pidfile = ./uwsgi.pid
#pid文件，用于systemd管理
