# Generated by Django 4.0.4 on 2026-06-30 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fdfs', '0002_file_deleted_at_file_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid4, max_length=32, unique=True, verbose_name='分享码')),
                ('password', models.CharField(blank=True, default='', max_length=6, verbose_name='访问密码')),
                ('expire_hours', models.IntegerField(default=24, verbose_name='有效期(小时)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdfs.file', verbose_name='分享文件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdfs.user', verbose_name='分享者')),
            ],
            options={
                'verbose_name': '分享',
                'verbose_name_plural': '分享',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='文件夹名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fdfs.folder', verbose_name='父文件夹')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdfs.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '文件夹',
                'verbose_name_plural': '文件夹',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fdfs.folder', verbose_name='所属文件夹'),
        ),
    ]
