# Generated by Django 4.0.4 on 2026-06-30 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fdfs', '0003_share_folder_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='分享码'),
        ),
    ]
