# Generated by Django 4.0.4 on 2026-06-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdfs', '0004_alter_share_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fdfs.folder', verbose_name='分享文件夹'),
        ),
        migrations.AlterField(
            model_name='share',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fdfs.file', verbose_name='分享文件'),
        ),
    ]
